chore: rename everything to rtx from asdf

diff --git a/shims/npm b/shims/npm
--- a/shims/npm
+++ b/shims/npm
@@ -3,7 +3,7 @@
 set -eu
 set -o pipefail
 
-# This script wraps npm so to run `asdf reshim` after global installs and uninstalls
+# This script wraps npm so to run `rtx reshim` after global installs and uninstalls
 # Any other cases are passed-through to npm
 
 this_dir=$(dirname "${BASH_SOURCE[0]}")
@@ -11,13 +11,10 @@ plugin_name=$(basename "$(dirname "$this_dir")")
 
 this_dir=$(cd "$this_dir" && pwd -P) # Normalizes the directory
 
-asdf_data_dir=$(cd "${ASDF_DATA_DIR:-$HOME/.asdf}" && pwd -P)
-asdf_shims_dir="$asdf_data_dir/shims"
-
-plugin_dir="$asdf_data_dir/plugins/$plugin_name"
+plugin_dir="${RTX_DATA_DIR}/plugins/$plugin_name"
 
 should_reshim() {
-  if [ "${ASDF_SKIP_RESHIM:-}" ]; then
+  if [ "${RTX_SKIP_RESHIM:-}" ]; then
     return 1
   fi
 
@@ -77,12 +74,12 @@ resolve_canon_npm() {
 
   # Try searching in current path (asdf core from 0.7 onwards adds all binaries candidates directories to PATH)
   # if that doesn't works (when calling the shim directly for example) it tries manually searching the binary in
-  # the installed version provided by "asdf where"
-  npm_location="${ASDF_NODEJS_CANON_NPM_PATH:-$(search_npm_on_current_path || manually_search_npm_bin)}"
+  # the installed version provided by "rtx where"
+  npm_location="${RTX_NODEJS_CANON_NPM_PATH:-$(search_npm_on_current_path || manually_search_npm_bin)}"
 
   if ! [ "$npm_location" ]; then
-    printf "asdf-nodejs couldn't find a suitable npm executable\n"
-    printf "This is probably a problem with the plugin, please report this issue at https://github.com/asdf-vm/asdf-nodejs/issues\n"
+    printf "rtx-nodejs couldn't find a suitable npm executable\n"
+    printf "This is probably a problem with the plugin, please report this issue at https://github.com/jdxcode/rtx-nodejs/issues\n"
     exit 1
   fi
 
@@ -96,7 +93,7 @@ remove_current_dir_from_path() {
     if [ -d "$dir" ]; then
       normalized_dir=$(cd "$dir" && pwd -P)
 
-      if [ "$normalized_dir" = "$this_dir" ] || [ "$normalized_dir" = "$asdf_shims_dir" ]; then
+      if [ "$normalized_dir" = "$this_dir" ] || [ "$normalized_dir" = "${RTX_SHIMS_DIR:-}" ]; then
         continue
       fi
     fi
@@ -110,7 +107,7 @@ remove_current_dir_from_path() {
 search_npm_on_current_path() {
   local filtered_path=
 
-  # Tries to prevent recursion by removing the current script and asdf-shim from PATH
+  # Tries to prevent recursion by removing the current script and rtx-shim from PATH
   filtered_path=$(remove_current_dir_from_path)
 
   PATH="$filtered_path" command -v npm
@@ -119,7 +116,7 @@ search_npm_on_current_path() {
 manually_search_npm_bin() {
   local installed_dir= bin_directories=
 
-  installed_dir=$(asdf where nodejs)
+  installed_dir=$(rtx where nodejs)
   bin_directories=(bin)
 
   if [ -x "$plugin_dir/bin/list-bin-paths" ]; then
@@ -142,8 +139,8 @@ wrap_npm_if_reshim_is_needed() {
 
   if should_reshim "$@"; then
     "$npm" "$@"
-    printf "Reshimming asdf %s...\n" "$plugin_name" >&2
-    asdf reshim "$plugin_name"
+    printf "Reshimming rtx %s...\n" "$plugin_name" >&2
+    asdf reshim
   else
     exec "$npm" "$@"
   fi
